apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
spec:
  containers:
  - name: myapp-container
    image: busybox:1.28
    command: ['sh', '-c', 'echo The app is running! && sleep 3600']
  initContainers:
  - name: init-myservice
    image: busybox:1.28
    command: ['sh', '-c', 'until nslookup myservice; do echo waiting for myservice; sleep 2; done;']
  - name: init-mydb
    image: busybox:1.28
    command: ['sh', '-c', 'until nslookup mydb; do echo waiting for mydb; sleep 2; done;']

####Example 1:
apiVersion: v1
kind: Pod
metadata:
  name: red
  labels:
    app: red
spec:
  containers:
  - name: red-container
    image: busybox:1.28
    command: ['sh', '-c', 'echo The app is running! && sleep 20']
  initContainers:
  - name: init-myservice
    image: busybox:1.28
    command: ['sh', '-c', 'echo The app is running! && sleep 20']
    
    
######Example 2:
apiVersion: v1
kind: Pod
metadata:
  name: orange
  labels:
    app: orange
spec:
  containers:
  - name: orange-container
    image: busybox:1.28
    command:
    - sh
    - -c
    - echo The app is running! && sleep 3600
  initContainers:
  - name: init-myservice
    image: busybox:1.28
    command:
    - sh
    - -c
    - sleep 2