apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-sleeper
spec:
  containers:
  - name: ubuntu-sleeper
    image: ubuntu-sleeper
    command:["sleep2.0"] # command overrides the entrypoint used in Dockerfile.
	args:["10"]          # args overrides the cmd used in Dockerfile.